import { StyleSheet, Dimensions } from "react-native"

const { width, height } = Dimensions.get("window")

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  container: {
    flex: 1,
    width: "100%",
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    width: "100%",
    paddingTop: 100,
    paddingBottom: 0,
    justifyContent: "space-between",
  },
  logo: {
    width: width * 0.5,
    height: height * 0.15,
    marginBottom: "auto",
  },
  formContainer: {
    width: "100%",
    height: "75%",
    backgroundColor: "white",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingHorizontal: 24,
    paddingTop: 25,
    paddingBottom: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    marginTop: "auto",
  },
  title: {
    fontSize: 30,
    fontFamily: "Mulish-Black",
    marginBottom: 25,
    color: "#000",
    alignSelf: "center",
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 43,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 25,
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  countryCodeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  countryCodeText: {
    fontSize: 16,
    color: "#333",
    fontFamily: "Inter-Medium",
  },
  downIcon: {
    marginLeft: 5,
  },
  phoneInput: {
    flex: 1,
    height: "100%",
    fontSize: 16,
    color: "#333",
    fontFamily: "Inter-Medium",
  },
  loginButton: {
    width: "100%",
    height: 43,
    backgroundColor: "#FF5722",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  loginButtonText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Inter-Black",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 15,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: "#ddd",
  },
  dividerText: {
    paddingHorizontal: 10,
    color: "#777",
    fontSize: 14,
    fontFamily: "Inter-Medium",
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 43,
    backgroundColor: "white",
    borderRadius: 25,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    paddingHorizontal: 15,
  },
  socialIconContainer: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  socialButtonText: {
    fontSize: 13,
    color: "#333",
    flex: 1,
    textAlign: "center",
    paddingRight: 40,
    fontFamily: "Inter-Medium",
  },
  registerContainer: {
    flexDirection: "row",
    marginTop: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  registerText: {
    fontSize: 13,
    color: "#333",
    fontFamily: "Inter-Medium",
  },
  registerLink: {
    fontSize: 13,
    color: "#007AFF",
    fontFamily: "Inter-Medium",
    textDecorationLine: 'underline'
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    width: "85%",
    maxHeight: "70%",
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 15,
  },
  countryItem: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  countryItemText: {
    fontSize: 16,
    color: "#333",
  },
  forgotPasswordContainer: {
    alignSelf: "center",
    marginBottom: 10,
  },
  forgotPasswordText: { 
    color: "#007AFF",
    fontSize: 14,
    paddingLeft:200,
    textDecorationLine: 'underline',
    fontFamily:'Inter-Medium'
  },
})

export default styles